# Generated by Django 5.1.6 on 2025-03-06 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField()),
                ('is_user', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('llm_response_time_s', models.FloatField(blank=True, null=True)),
                ('function_called', models.JSONField(blank=True, null=True)),
                ('function_result', models.JSONField(blank=True, null=True)),
                ('token_used', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
