# Generated by Django 5.1.6 on 2025-03-19 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_video', models.TextField(blank=True, null=True)),
                ('long_video', models.TextField(blank=True, null=True)),
                ('difficulty', models.TextField(blank=True, null=True)),
                ('target_muscle', models.TextField(blank=True, null=True)),
                ('primary_equipment', models.TextField(blank=True, null=True)),
                ('secondary_equipment', models.TextField(blank=True, null=True)),
                ('body_region', models.TextField(blank=True, null=True)),
                ('mechanics', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generate_schedule', models.BooleanField(default=False)),
                ('current_week', models.IntegerField(blank=True, null=True)),
                ('current_week_start', models.DateField(blank=True, null=True)),
                ('current_week_end', models.DateField(blank=True, null=True)),
                ('workout_days', models.JSONField(blank=True, null=True)),
                ('difficulty', models.TextField(blank=True, null=True)),
                ('exclude_equipment', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('skipped', 'Skipped'), ('missed', 'Missed'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='python_project.exercise')),
                ('workout_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='python_project.workoutweek')),
            ],
        ),
    ]
