# Generated by Django 5.1.6 on 2025-03-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_project', '0003_fooddatabase_exercise_exercise_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddatabase',
            name='sodium_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
