# Generated by Django 5.1.6 on 2025-03-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_project', '0004_alter_fooddatabase_sodium_per_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddatabase',
            name='sodium_per_100g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
