# Generated by Django 5.1.6 on 2025-03-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_project', '0010_alter_userprofile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddatabase',
            name='weight_per_unit_g',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
    ]
