# Generated by Django 5.1.6 on 2025-03-26 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('python_project', '0011_fooddatabase_weight_per_unit_g'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooddatabase',
            name='weight_per_unit_g',
        ),
    ]
