# Generated by Django 5.1.6 on 2025-03-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_project', '0012_remove_fooddatabase_weight_per_unit_g'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodentry',
            name='label',
        ),
        migrations.AddField(
            model_name='foodentry',
            name='serving',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
