# Generated by Django 5.1.6 on 2025-03-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_project', '0014_foodentry_label_foodentry_measurement_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodentry',
            old_name='food_id',
            new_name='food',
        ),
        migrations.AlterField(
            model_name='foodentry',
            name='measurement_unit',
            field=models.CharField(choices=[('weight', 'weight'), ('serving', 'serving')], max_length=10),
        ),
    ]
