# Generated by Django 5.1.6 on 2025-03-26 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('python_project', '0015_rename_food_id_foodentry_food_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodentry',
            old_name='food',
            new_name='food_id',
        ),
    ]
