# Generated by Django 5.1.6 on 2025-06-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_project', '0016_rename_food_foodentry_food_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddatabase',
            name='image_url',
            field=models.URLField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='activity_level',
            field=models.CharField(choices=[('Sedentary', 'Sedentary'), ('Lightly Active', 'Lightly Active'), ('Moderately Active', 'Moderately Active'), ('Very Active', 'Very Active')], max_length=20),
        ),
    ]
