# Generated by Django 5.1.6 on 2025-06-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_project', '0019_fooddatabase_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='duration_seconds',
            field=models.IntegerField(default=45),
        ),
        migrations.AddField(
            model_name='workout',
            name='rest_seconds',
            field=models.IntegerField(default=20),
        ),
    ]
