# Generated by Django 5.1.6 on 2025-06-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_project', '0020_workout_duration_seconds_workout_rest_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workout',
            name='last_paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='progress_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
