# Generated by Django 5.1.6 on 2025-06-16 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_project', '0021_workout_in_progress_workout_last_paused_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.IntegerField(default=1)),
                ('rep_number', models.IntegerField(default=1)),
                ('seconds_left_in_rest', models.IntegerField(default=0)),
                ('status', models.CharField(default='paused', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='python_project.workout')),
            ],
            options={
                'unique_together': {('user', 'workout')},
            },
        ),
    ]
