# Generated by Django 5.1.6 on 2025-06-16 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_project', '0022_workoutprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight', models.FloatField()),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_logs', to='python_project.userprofile')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
